### ISSUE TITLE
problem with regular expressions

### ISSUE THREAD

**Issue by Dario-Rosa85** [AtomLinter/linter-julia#111]
I get an error message when my code include a regular expression.
Here an example:

input = "4457418557635128"
visa = r"^(?:4[0-9]{12}(?:[0-9]{3})?)$"
if occursin(visa, input)
    println("credit card found")
    m = match(visa, input)
    println(m.match)
    println(m.offset)
    println(m.offsets)
end

I get this error message

: MethodError(convert, (Type, nothing), 0x0000000000006a26)

does anybody know how to fix it?

**Comment by aminya** [comment]
Please do not use the linter. `Lint.jl` is not working, and we have not found a way to integrate StaticLint.jl

https://github.com/julia-vscode/StaticLint.jl/issues/14
https://github.com/julia-vscode/StaticLint.jl/issues/37

I don't know how to use StaticLint. The documentation is missing

**Comment by aminya** [comment]
Fixed in #119
