### ISSUE TITLE
Linter spams all cpu, making my laptop unworkable

### ISSUE THREAD

**Issue by schlichtanders** [AtomLinter/linter-julia#114]
Hi,

I just gave linter-julia another try, because I really miss the linting in Atom.
It's aweful unfortunately. Not only does it not work, but it blocks all CPU nodes, on my powerful Mac.

I hope someone in the future, this will just work, hence I open this ticket for someone to be able to address it.

This screenshot is done while atom is still open:
<img width="943" alt="Screenshot 2020-06-13 at 15 18 57" src="https://user-images.githubusercontent.com/4255480/84569848-b3fc4280-ad89-11ea-9986-0351e3faa086.png">

This screenshot is done after atom was quit:
<img width="956" alt="Screenshot 2020-06-13 at 15 22 49" src="https://user-images.githubusercontent.com/4255480/84569857-c5dde580-ad89-11ea-97e7-42be89ef24eb.png">
After about 5 min, all processes seemed to be stopped finally...

As you can see, it is not useable and not recommendable. I hope that somewhen it will work.

Unfortunately I cannot tell you which julia version was used. Usually I have julia 1.4.1 currently running in Juno and on commandline, however no linter package seemed to be installed there when I check the status. So maybe some other julia version (I have a couple installed)... 

OS: Mac Catalina

**Comment by schlichtanders** [comment]
I now installed  `] add https://github.com/tonyhffong/Lint.jl` in my julia 1.4.1 and hardcoded the julia path in the vscode setting of linter-julia, however still same results...

**Comment by aminya** [comment]
Please do not use the linter. `Lint.jl` is not working, and we have not found a way to integrate StaticLint.jl

https://github.com/julia-vscode/StaticLint.jl/issues/37

**Comment by schlichtanders** [comment]
thanks for the notice, still cost me 2 hours today.

Please, if you mind, update the official extension page https://atom.io/packages/linter-julia with big fat CURRENTLY NOT WORKING.

This is really annoying to be suggested it may work and then find that your complete system goes crazy.

**Comment by schlichtanders** [comment]
I took a look at the link you send, it says there is no API, however the front-page of StaticLint.jl actually has a longer explanation https://github.com/julia-vscode/StaticLint.jl

**Comment by aminya** [comment]
@schlichtanders I will try to implement the language server and update this package. Stay tuned.

**Comment by schlichtanders** [comment]
thank you so much

please also update the extension page https://atom.io/packages/linter-julia  respectively, it is so annoying you have to understand.

**Comment by aminya** [comment]
OK. I added a warning to the readme. I will publish it to atom.io aswell

**Comment by aminya** [comment]
Fixed in #119
