### ISSUE TITLE
Simply not working

### ISSUE THREAD

**Issue by aquaresima** [AtomLinter/linter-julia#121]
Hi, 
I am running Julia 1.5.4
Atom 1.44
and Julia-client 0.12.6 (no update requests for any package)

I installed:
`linter`
`linter-julia`
`linter-ui-julia`

Then I open a new file and write exactly the same that is written in the package example (`using Foo, print(...  `). The blue box announcing that linter is compiling the environment variables appears, and then NOTHING happens.

In the lower-left three tray icons announce to me that there are not linter warnings, errors or info.

Can you help me?

Thanks

**Comment by takbal** [comment]
@aquaresima please read the "Caveats" section in the doc:

1. You need to save the file at least once. Linting does not work on a buffer that has no file name associated with. This is a limitation of the parent 'linter' package.
2. When you open a project the first time, you have to wait for some time the parsing to happen.
3. After the parsing finished, you may need to edit or save the file again for the linting messages to appear. The end of the parse is not announced, but a minute must be more than enough for a small project.

Points 2 and 3 are only needed when you open a project the first time. Linting for further files should be immediate.

I am also recommending the 'atom-ide-ui' package for displaying the messages.

Please comment if this helped or not.

**Comment by aquaresima** [comment]
Hi, 
Thanks a lot for answering. 
I should have specified. I read and applied those caveats.
I open a new project, with a single file in it: test_lint.jl
then I write in the file. Save the file. The Linter announced that it started parsing the file....
and then nothing.

**Comment by takbal** [comment]
@aquaresima did you wait, say, a minute then, then tried editing the file again?

**Comment by takbal** [comment]
At the very-very-very first case, you should also wait longer for the packages to install into .julia/environments/linter-julia.

**Comment by aquaresima** [comment]
Ok, worked! Indeed, it took a lot, after that it's faster when I open a new project
