### ISSUE TITLE
Install Lint.jl automatically

### ISSUE THREAD

**Issue by dpsanders** [AtomLinter/linter-julia#30]
I just tried to install `linter-julia` on a new computer (in front of a class...) and forgot to install `Lint.jl`. I did not realise my error until I finally looked at the Developer console.

I suggest that the package automatically install `Lint.jl`, following the same strategy as `uber-juno`, which installs a couple of Julia packages.

**Comment by dpsanders** [comment]
For reference, the error was something like "Cannot connect EN0ENT in lintserver"

**Comment by TeroFrondelius** [comment]
I like this idea. I need to look into the details.

**Comment by TeroFrondelius** [comment]
Implementation: d8fb9a22c0382167e2b4e1f048877640be3b941f

**Comment by TeroFrondelius** [comment]
This is not working (at least on windows):
```
ERROR: MethodError: no method matching isless(::VersionNumber, ::Void)
Closest candidates are:
  isless(::VersionNumber, !Matched::VersionNumber) at version.jl:142
 in >(::Void, ::VersionNumber) at .\operators.jl:64
 in eval(::Module, ::Any) at .\boot.jl:234
 in process_options(::Base.JLOptions) at .\client.jl:239
 in _start() at .\client.jl:318
```

**Comment by aminya** [comment]
This is done now. Closed by https://github.com/AtomLinter/linter-julia/commit/a2619ea158960b0146a20c2a43590944742faec3
