### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by volkan-a** [AtomLinter/linter-julia#43]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [linter-julia](https://github.com/TeroFrondelius/linter-julia) package 0.7.2

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html:1

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at /packages/linter-julia/lib/linter-julia.coffee:93:26)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -0:26.1.0 julia-client:run-and-move (input.hidden-input)
     -0:20.7.0 editor:newline (input.hidden-input)
  3x -0:16.1.0 core:backspace (input.hidden-input)
     -0:14.2.0 julia-client:run-and-move (input.hidden-input)
     -0:12.1.0 inline:clear-current (input.hidden-input)
     -0:12.1.0 editor:consolidate-selections (input.hidden-input)
     -0:12.1.0 core:cancel (input.hidden-input)
     -0:10.9.0 inline:clear-current (input.hidden-input)
     -0:10.9.0 editor:consolidate-selections (input.hidden-input)
     -0:10.9.0 core:cancel (input.hidden-input)
     -0:10.2.0 inline:clear-current (input.hidden-input)
     -0:10.2.0 editor:consolidate-selections (input.hidden-input)
  2x -0:10.2.0 core:cancel (input.hidden-input)
  2x -0:05.7.0 core:move-right (input.hidden-input)
  2x -0:05.1.0 core:backspace (input.hidden-input)
     -0:03.6.0 autocomplete-plus:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-dark-fusion-syntax 2.2.0 
autocomplete-python 1.8.63 
busy-signal 1.4.1 
git-plus 7.8.0 
Hydrogen 1.12.1 
ink 0.6.5 
intentions 1.1.2 
julia-client 0.5.12 
language-julia 0.11.0 
latex-completions 0.3.2 
linter 2.1.4 
linter-flake8 2.2.1 
linter-julia 0.7.2 
linter-ui-default 1.2.4 
nucleus-dark-ui 0.12.1 
python-debugger 0.2.0 
python-indent 1.0.2 
python-tools 0.6.9 
tool-bar 1.1.0 
uber-juno 0.1.1 
```

**Comment by TeroFrondelius** [comment]
See #38. Have you installed Lint.jl? 
```julia
julia> Pkg.add("Lint")
```

**Comment by volkan-a** [comment]
Yes, but occasionally I get that error message.

**Comment by aterenin** [comment]
+1

Same issue here, occurs at random times. Lint.jl is installed and I've run `Pkg.checkout("Lint")` and `using Lint` at least once.

**Comment by TeroFrondelius** [comment]
I recommend testing the master versions. It's totally rewritten and only the testing is pending to release it.

**Comment by gdkrmr** [comment]
maybe this has something to do with this: https://github.com/gdkrmr/flycheck-julia/issues/1

**Comment by dpsanders** [comment]
How can we install the master version?

**Comment by gdkrmr** [comment]
`Pkg.checkout("Lint")` will install the latest master

**Comment by dpsanders** [comment]
I assumed that the reference was to the master version of the atom linter-julia package, rather than to Lint.jl. Am I wrong?

**Comment by TeroFrondelius** [comment]
Sorry for the late answer I have been travelling. @dpsanders is correct I meant linter-julia master version. Installing it should be as easy as copy-pasting the link to the github repo to the Atom install package search window.

**Comment by aterenin** [comment]
Just updated my Atom package version and will let you know if the error persists. As an FYI to anyone else who updates, be aware that the latest Git version of linter-julia does not correctly inherit the Julia executable path from Juno. You need to set it manually in the options.

**Comment by kingwyf87** [comment]
Tried to use linter-julia in Atom on MacOS. Initially, got the errors similarly as in #43 and #38. Followed previous discussions: uninstalled "linter-ui-default" and installed the latest master "Lint.jl" but still get the below errors:

 [Linter-Julia] Server returned non-JSON response:  
/Users/yifei-macpro/.atom/packages/linter-julia/lib/index.js:107

[Linter] Error running Julia Error: Error parsing server response. See console for more info
    at Socket.<anonymous> (/Users/yifei-macpro/.atom/packages/linter-julia/lib/index.js:96:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

[Linter] Error running Julia Error: Request timed out linter-registry.js [sm]:137 
    at /Users/yifei-macpro/.atom/packages/linter-julia/lib/index.js:80:18

**Comment by gdkrmr** [comment]
I am the author of `flycheck-julia` which is implements `Lint.jl` for Emacs. After I start the server, the first couple of queries give the (probably) same error. When looking at the actual String I get back from the server, it is sometimes empty "" or contains just "[{" or an incomplete json object.

**Comment by ufechner7** [comment]
This is annoying. Updated to Julia 0.6, still have this problem on Ubuntu 16.04. Any suggestion what to try fixing it?

**Comment by gdkrmr** [comment]
for emacs' `flycheck-julia` the problem appears the first ~20 seconds after starting the server, this is probably due to compilation, then everything works just fine. I observe the same behavior for atom so I think that this is `Lint.jl` issue but I do not think that it is critical.

**Comment by gdkrmr** [comment]
I finally fixed the problem for `flycheck-julia`, the trick was to wait until the connection gets closed by the server.

**Comment by jessebett** [comment]
Any fix for this?

**Comment by Arcanemagus** [comment]
It looks like since the last comment here this package has been entirely re-written in JavaScript, and I'll be pushing out a release shortly with several fixes. If you are on a version _newer_ than v0.7.3 and still seeing this let us know!
