### ISSUE TITLE
Does not work with modules

### ISSUE THREAD

**Issue by AShedko** [AtomLinter/linter-julia#44]
Linter does not work well with modules. Is there a possibility of making that happen in forseeable future?

**Comment by TeroFrondelius** [comment]
Can you share little bit more details? I have a feeling this is Lint.jl issue but it would be easier to comment if you can show by example what is exactly the problem.

**Comment by AShedko** [comment]
I meant things like having code from a local module show up as undeclared symbols.

**Comment by TeroFrondelius** [comment]
Try running Lint.jl from REPL. Do you get the same errors and warnings? 

Your example is too small to understand your workflow. If you either include or import by using the local module before your functions usage it should work.

**Comment by AShedko** [comment]
It works fine from the REPL
![image](https://user-images.githubusercontent.com/7196534/27049034-ba913666-4fb6-11e7-8f61-350f12bb1343.png)

**Comment by TeroFrondelius** [comment]
I still don't understand your problem. In your example each line have a red dot meaning there are some errors. Maybe you just don't see the error messages? What happens when you move cursor to any of the red dotted lines?

**Comment by AShedko** [comment]
![image](https://user-images.githubusercontent.com/7196534/27281474-ad6e18f8-54f4-11e7-90f4-07138f2e6436.png)
The dotted lines are where the functions and constants from ISCLib are used

**Comment by aminya** [comment]
Fixed in #119
