### ISSUE TITLE
Help needed with linter-julia

### ISSUE THREAD

**Issue by TeroFrondelius** [AtomLinter/linter-julia#47]
Anyone willing to take the maintaining responsibility? I am open to all proposal  i.e. let's move this repo under some organisation or someone will be added more rights to maintain and develop this further or something else. 

I have been too busy with my work and I haven't had any time to code and it seems that the situation won't change in the near future. One major task left is to test master branch, totally rewritten code and tag it and start fixing the possible bugs. If you have already used the master branch, the the testing is already pretty much done. Like I said, unfortunateky I haven't had time to code, thus I haven't done the testing.

**Comment by Arcanemagus** [comment]
I'd be perfectly happy to bring it into the `AtomLinter` organization, that way at least it can get some minimal attention and when somebody hopefully steps up to work on it there will be an organization to take on getting them started 😉.

**Comment by TeroFrondelius** [comment]
Done

**Comment by Arcanemagus** [comment]
Transfer finished, and you have a pending invite into the organization. You have direct Admin rights on this repo already though 😉.

Once you accept that invite I'll make you a maintainer of the team related to this repo so you can add other people (within the org only unfortunately) to the team. If you want to bring in anyone outside the org please bug me in [Atom's Slack](https://discuss.atom.io/t/join-us-on-slack/16638) and I'll get to it ASAP!

I'll make the necessary changes to `package.json` and push out a release to update the repo location.

**Comment by Arcanemagus** [comment]
I'm leaving this open for now so anyone watching this repo can jump up and become a maintainer here 😉.

**Comment by aminya** [comment]
I think I can close this 😄
