### ISSUE TITLE
Doesn't lint editor contents

### ISSUE THREAD

**Issue by Kelvyn88** [AtomLinter/linter-julia#48]
Hi everyone,

I have the latest version of atom on windows 10. I installed linter and all the dependencies, Linter-julia following by linter-ui. The problem is that I can't see the messsges for errors or warnings after I save the .jl file. This is annoying.

Please tell me if this can't be done in windows or I have to so something.

**Comment by Arcanemagus** [comment]
Do you have [`Lint.jl`](https://github.com/tonyhffong/Lint.jl) installed?

**Comment by Kelvyn88** [comment]
Yes! I even try to checkout the packages but it doesn't work.

I have to save the file every time that I change something to see the errors or warnings, but not as a message, it appears in the lower linter menu.

**Comment by TeroFrondelius** [comment]
Go to the linter settings (not linter-julia) and change this behaviour. I don't remember what it is called. When you will find the solution, please report it here thus others will find it easier.

**Comment by Kelvyn88** [comment]
All settings are set properly. Still doest'n work.

**Comment by Arcanemagus** [comment]
> I have to save the file every time that I change something to see the errors or warnings, but not as a message, it appears in the lower linter menu.

This is the _expected_ behavior, what are you thinking it should be doing? What are you thinking it should be appearing "as a message" then?

**Comment by Kelvyn88** [comment]
According to the gif presented in Linter-julia, as you type code, errors or warnings appears in live mode.

**Comment by Arcanemagus** [comment]
It looks like that was changed in https://github.com/AtomLinter/linter-julia/pull/41, but no reasoning was given so it's possible that was a mistake. You can try changing that to `true` again and seeing how things work. Make sure that it's _actually_ linting the contents of the editor and not just the contents on disk!

If it looks to be working send up a PR changing that value for everyone 😉.
